model: inceptionresnetv2
num_classes: 2
# 批量大小
batch_size: 1
# 工作进程数量
num_workers: 0

criterion:
  name: CrossEntropyLoss

#测试模型的权重文件
test_model_weight: model_teacher\model_weights_1_76.77%.pt

dataset:
  # 数据集根目录
  root_dir: minivideos/mini_train_vedios/
  # json文件路径
  json_file: minivideos/mini_train_vedios/metadata.json
  # 步长
  step: 30
  # 人脸裁剪 未发现人脸的将用全黑图片代替
  face_crop: true
  transform:
    - name: Resize
      size: [299, 299]