model: efficientnet-b7
num_classes: 2
# 批量大小
batch_size: 1
# 是否随机打乱数据
shuffle: true
# 工作进程数量
num_workers: 0

optimizer:
  name: Adam
  params:
    lr: 0.001

criterion:
  name: CrossEntropyLoss

# 训练轮数
num_epochs: 10
#保存训练模型的文件夹
trained_model_dir: ./models/model_student/

loader:
  # 步长
  step: 30
  # 人脸裁剪 未发现人脸的将用全黑图片代替
  face_crop: true
  transform:
    - name: Resize
      size: [64, 64]

dataset:
  - # 数据集根目录
   root_dir: minivideos/mini_train_vedios_1/
   # json文件路径
   metadata: minivideos/mini_train_vedios_1/metadata.json
  - # 数据集根目录
   root_dir: minivideos/mini_train_vedios_2/
   # json文件路径
   metadata: minivideos/mini_train_vedios_2/metadata.json
val_dataset:
  - # 数据集根目录
    root_dir: minivideos/mini_train_vedios_1/
    # json文件路径
    metadata: minivideos/mini_train_vedios_1/metadata.json